// All tags from model — exact names
export const ALL_TAGS: string[] = [
  "expression/avant-garde",
  "expression/chaotic",
  "expression/conceptual",
  "expression/difficulty spike",
  "expression/high contrast",
  "expression/iNiS-style",
  "expression/old-style revival",
  "expression/playfield usage",
  "expression/progression",
  "expression/repetition",
  "expression/simple",
  "gimmick/circle only",
  "gimmick/ninja spinners",
  "jumps/back and forth",
  "jumps/cross-screen",
  "jumps/freeform",
  "jumps/linear",
  "jumps/sharp",
  "jumps/squares",
  "jumps/stamina",
  "jumps/triangles",
  "jumps/wide",
  "meta/accelerating bpm",
  "meta/swing",
  "meta/time signatures",
  "meta/variable timing",
  "reading/overlaps",
  "reading/perfect stacks",
  "reading/visually dense",
  "skillset/alt",
  "skillset/jumps",
  "skillset/precision",
  "skillset/reading",
  "skillset/streams",
  "skillset/tech",
  "sliders/complex slidershapes",
  "sliders/complex sv",
  "sliders/high sv",
  "sliders/low sv",
  "streams/bursts",
  "streams/cutstreams",
  "streams/doubles",
  "streams/flow aim",
  "streams/spaced streams",
  "streams/speed",
  "streams/stamina",
  "style/avant-garde",
  "style/clean",
  "style/distance snap",
  "style/freeform",
  "style/geometric",
  "style/grid snap",
  "style/hexgrid",
  "style/messy",
  "style/symmetrical",
  "tech/aim control",
  "tech/finger control",
  "tech/slider tech",
].sort();
